#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $Kaal_REPO == "KaalBot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0thYWwwNDA4L0thYWwtVXNlcmJvdC9hcmNoaXZlL21haW4uemlw" | base64 -d
    elif [[ $Kaal_REPO == "Kaalbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0thYWwwNDA4L0thYWwtVXNlcmJvdC9hcmNoaXZlL21haW4uemlw" | base64 -d
    elif [[ $Kaal_REPO =~ $regex ]]
    then
        if [[ $Kaal_REPO_BRANCH ]]
        then
            echo "${Kaal_REPO}/archive/${Kaal_REPO_BRANCH}.zip"
        else
            echo "${Kaal_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0thYWwwNDA4L0thYWwtVXNlcmJvdC9hcmNoaXZlL21haW4uemlw" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="myKaalbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    KaalPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $KaalPATH
    echo "  • Starting KaalBot •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m Kaalbot
}

start_bot
